[build]
rustflags = [
    # Rustc lints
    # "-W", "warning_name"

    # Clippy lints
    "-W", "clippy::cloned_instead_of_copied",
    "-W", "clippy::enum_glob_use",
    "-W", "clippy::explicit_iter_loop",
    "-W", "clippy::map_unwrap_or",
    "-W", "clippy::redundant_closure_for_method_calls",
    "-W", "clippy::unnested_or_patterns",
    "-W", "clippy::uninlined_format_args",

    # Rejected for now, and why
    # "-W" "clippy::default_trait_access" - sometimes makes imports necessary, just for a default value. It's good for more explicit typing though.
    # "-W" "clippy::range_plus_one" - useful, but caused too many false positives as we use range types directly quite a lot


    # Rustdoc lints
    # "-W", "rustdoc::warning_name"
    # "-A", "rustdoc::warning_name"
]
