name: gitoxide
adopt-info: gitoxide
summary: gitoxide is an implementation of git written in Rust
description: |
    gitoxide is an implementation of git written in Rust for developing future-proof applications 
    which strive for correctness and performance while providing a pleasant and unsurprising 
    developer experience.
    gitoxide provides the gix and ein binaries for use on the command-line to allow experimentation
    with key features like fetch and clone, and to validate the usability and control of the API
    offered by the gix crate.
    gitoxide aspires to be a production-grade server implementation and the ein binary aspires to
    become the default way to interact with git repositories. 
    
    To run it from your terminal, type: `gix` or `ein` to access binaries in the `gitoxide` suite
    
license: Apache-2.0

base: core20
grade: stable
confinement: strict
compression: lzo

apps:
  gitoxide:
    command: bin/gix
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
  
  ein:
    command: bin/ein
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
   
  object:
    command: bin/gix-object
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
  
  validate:
    command: bin/gix-validate
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  url:
    command: bin/gix-url
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  packetline:
    command: bin/gix-packetline
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  packetline-blocking:
    command: bin/gix-packetline-blocking
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  transport:
    command: bin/gix-transport
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  protocol:
    command: bin/gix-protocol
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  pack:
    command: bin/gix-pack
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  odb:
    command: bin/gix-odb
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  commitgraph:
    command: bin/gix-commitgraph
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  diff:
    command: bin/gix-diff
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  traverse:
    command: bin/gix-traverse
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  features:
    command: bin/gix-features
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  credentials:
    command: bin/gix-credentials
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  sec:
    command: bin/gix-sec
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  quote:
    command: bin/gix-quote
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  discover: 
    command: bin/gix-discover
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home

  path:                                                                                                         
    command: bin/gix-path
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  attributes:
    command: bin/gix-attributes  
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  ignore:
    command: bin/gix-ignore
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  pathspec:
    command: bin/gix-pathspec
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  index:
    command: bin/gix-index
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  revision:
    command: bin/gix-revision
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  revwalk:
    command: bin/gix-revwalk
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  command:
    command: bin/gix-command
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  prompt:
    command: bin/gix-prompt
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  refspec:
    command: bin/gix-refspec
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  fs:
    command: bin/gix-fs
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home

  utils:
    command: bin/gix-utils
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  hashtable:
    command: bin/gix-hashtable
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
  worktree:
    command: bin/gix-worktree
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  bitmap:
    command: bin/gix-bitmap
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  negotiate:
    command: bin/gix-negotiate
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  filter:
    command: bin/gix-filter
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  worktree-stream:
    command: bin/gix-worktree-stream
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  archive:
    command: bin/gix-archive
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  submodule:
    command: bin/gix-submodule
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  status:
    command: bin/gix-status
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
      
  worktree-state:
    command: bin/gix-worktree-state
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home    
      
  date:
    command: bin/gix-date
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home                                                                                                  

parts:
  gitoxide:
    source: https://github.com/Byron/gitoxide
    source-type: git
    plugin: rust
    after: [cargo]

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f3)"
    
    build-packages:
      - cmake
      
  cargo:
    source: https://github.com/rust-lang/cargo
    source-type: git
    plugin: rust
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f2)"

    build-packages:
      - cargo
      - rustc
      - pkg-config
      - librust-openssl-sys-dev      
