name: gitoxide
adopt-info: gitoxide
summary: gitoxide is an implementation of git written in Rust
description: |
    gitoxide is an implementation of git written in Rust for developing future-proof applications 
    which strive for correctness and performance while providing a pleasant and unsurprising 
    developer experience.
    gitoxide provides the gix and ein binaries for use on the command-line to allow experimentation
    with key features like fetch and clone, and to validate the usability and control of the API
    offered by the gix crate.
    gitoxide aspires to be a production-grade server implementation and the ein binary aspires to
    become the default way to interact with git repositories. 

license: Apache-2.0

base: core20
grade: stable
confinement: strict
compression: lzo

apps:
  gitoxide:
    command: usr/local/bin/gitoxide
    environment:
      PATH: $SNAP/usr/bin:$SNAP/usr/local/bin/:$PATH:$SNAP/bin/:$PATH    
    plugs:
      - network
      - home

parts:
  gitoxide:
    source: https://github.com/Byron/gitoxide
    source-type: git
    plugin: rust
    after: [cargo]
    
    override-build: |
      cargo install --git https://github.com/Byron/gitoxide  gitoxide
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
    
    build-packages:
      - cmake
      
  cargo:
    source: https://github.com/rust-lang/cargo
    source-type: git
    plugin: rust
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f2)"

    build-packages:
      - cargo
      - rustc
      - pkg-config
      - librust-openssl-sys-dev      
